export enum MAP_ENUMS {
  INITIAL_MAP_POSITION_X = 165,
  INITIAL_MAP_POSITION_Y = -300,
  MAP_WIDTH = 20,
  TILE_SIZE = 32,
  COLLISION_TILE_VALUE = 1816,
  MAP_1_NPC_1_INTERACTION_TILE_VALUE = 1816,
  MAP_1_COMPUTER_1_INTERACTION_TILE_VALUE = 1817,
  MAP_1_COMPUTER_2_INTERACTION_TILE_VALUE = 1818,
  IMAGE_ZOOM_PERCENTS = 200,
  STARTING_POINT_Y_OFFSET_FROM_TOP_OF_MAP = 224,
}
