export enum MAP_ENUMS {
  INITIAL_MAP_POSITION_X = 165,
  INITIAL_MAP_POSITION_Y = -300,
  MAP_WIDTH = 20,
  TILE_SIZE = 32,
  IMAGE_ZOOM_PERCENTS = 200,
  STARTING_POINT_Y_OFFSET_FROM_TOP_OF_MAP = 224,
}
