export enum COMPANION_DECORATOR_ENUMS {
  DIALOG_INTERACTION_ICON_SIZE = 32,
  DIALOG_INTERACTION_ICON_OFFSET_Y = -26,
  DIALOG_INTERACTION_ICON_HOVER_VELOCITY = 1,
  DIALOG_INTERACTION_ICON_IDLE_ANIMATION_STEPS = 10,
}
