export enum PLAYER_ENUMS {
  NUMBER_OF_MOVEMENT_SPRITE_PRESETS = 24,
  NUMBER_OF_MOVEMENT_SPRITE_PRESETS_PER_MOTION = 6,
  MOVEMENT_VELOCITY = 3,
  MOVEMENT_DIRECTION_UP = "UP",
  MOVEMENT_DIRECTION_DOWN = "DOWN",
  MOVEMENT_DIRECTION_RIGHT = "RIGHT",
  MOVEMENT_DIRECTION_LEFT = "LEFT",
}
